name: holaMundo
run-name: estoy aprendiendo github actions
on: [push]
jobs:
    hola_mundo:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Definir variable
            run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV

          - name: Correr script
            run: python hola_mundo.py
    